/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ecto.gltf --transform 
Files: ecto.gltf [125.5KB] > /home/zuhedev/Documents/portefolio/portefolio/public/haunter_fbx/ecto-transformed.glb [66.01KB] (47%)
Author: spritemare (https://sketchfab.com/spritemare)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/haunter-fbx-aed9849d58ba469baa3a191198c57d4d
Title: Haunter fbx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ecto(props) {
  const { nodes, materials } = useGLTF('/ecto-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.s0026_Cartoon_814CA5_0.geometry} material={materials.PaletteMaterial001} position={[0.256, 0.377, 0.141]} rotation={[-1.902, -0.065, -3.088]} />
      <mesh geometry={nodes.s0043_Cartoon_813758_0.geometry} material={materials.PaletteMaterial002} position={[0.246, 0.176, 0.116]} rotation={[-2.358, 0.339, -2.979]} />
      <mesh geometry={nodes.s0053_Cartoon_FFFFFF_0.geometry} material={materials.PaletteMaterial003} position={[0.56, 0.41, 0.576]} rotation={[-2.734, -0.122, -3.096]} />
    </group>
  )
}

useGLTF.preload('/ecto-transformed.glb')
