/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 flutter.gltf --transform 
Files: flutter.gltf [922.54KB] > /home/zuhedev/Documents/portefolio/portefolio/public/apple_iphone_13_pro_max/flutter-transformed.glb [86.29KB] (91%)
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-iphone-13-pro-max-4328dea00e47497dbeac73c556121bc9
Title: Apple iPhone 13 Pro Max
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Flutter(props) {
  const { nodes, materials } = useGLTF('/flutter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Frame_Frame_0.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Frame_Mic_0.geometry} material={materials.material} />
      <mesh geometry={nodes.Body_Wallpaper_0.geometry} material={materials.Wallpaper} />
      <mesh geometry={nodes.Body_Camera_Glass_0.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Body_Lens_0.geometry} material={materials.Lens} />
    </group>
  )
}

useGLTF.preload('/flutter-transformed.glb')
